### ISSUE TITLE
Conflicting with xamarin.forms.maps

### ISSUE THREAD

**Issue by alexbleks** [LosXamarinos/Xamarinos.AdMob.FormsPlugin#1]
When I install this it messes up my Google Play Services saying: 

error APT0000: Attribute "imageAspectRatioAdjust" has already been defined
error APT0000: Attribute "imageAspectRatio" has already been defined
error APT0000: Attribute "circleCrop" has already been defined

**Comment by mathieu-xamarinos** [comment]
We are looking into this, most probably a conflict with another package you have referencing a different version of google play services. A patch will be released shortly.

**Comment by alexbleks** [comment]
Everything works well until I added this Admob package.

These are the googleplayservices that I have installed (when admob is removed):

![skjermbilde 2016-02-17 kl 23 05 28](https://cloud.githubusercontent.com/assets/17303226/13126548/27c701d2-d5cb-11e5-95f4-efed0cd7fd18.png)


Thanks :-)

**Comment by AlejandroRuiz** [comment]
Fixed on version 1.0.3 please follow next steps:
1. Remove both Xamarin.Forms.Maps and Xamarinos.AdMob.FormsPlugin
2. Remove all Xamarin.GooglePlayServices.* dependencies
3. Add Xamarinos.AdMob.FormsPlugin Ver. 1.0.3
4. Add Xamarin.Forms.Maps Ver. 2.0.1.6505
