### ISSUE TITLE
ios application crash

### ISSUE THREAD

**Issue by nagaitomoyuki** [LosXamarinos/Xamarinos.AdMob.FormsPlugin#3]
Hello.

I used Xamarinos.AdMob.FormsPlugin
But, iOS is crash at app lunching.
Do you know the cause?

source code 
https://github.com/nagaitomoyuki/admob-xamarinforms

crash screenshot
https://gyazo.com/f4986f98b5eca4d4ec917dd1489c49c8

——
こんにちは。
admobプラグインを使ってiOSアプリを作ったのですが
アプリを起動するとクラッシュしてしまいます。
原因わかるでしょうか？

ソースコードとクラッシュのスクリーンショットを貼り付けました。

**Comment by mathieu-xamarinos** [comment]
こんばんわ

Are you using by any chance ios 10 ? We havn’t got a chance to upgrade the plugin to this version yet.
We’ll be checking in the next few days and keep you posted.
If you find a fix on your own, please let us know as well, and we’ll integrate your patch :)

Best Regards,

**Comment by nagaitomoyuki** [comment]
Hello!

As the following that I went
* Xamarin.Forms update
* icon change(it's pretty)

If you want to include this plug-in to the project, don't call in Xamarin.Forms.Application.Constructor.
Becouse, GADBannerView will call after UIWindow#makekeyandvisible().
example:https://github.com/stjan/XamarinAdmobExample/blob/master/admob/App.xaml.cs#L18


This issue is finish!
